### PR TITLE
Smaller triangle

### PR DESCRIPTION
**Pull request by mischah**
@Haroenv  That’s it.

I thought it would be cool to have a box shadow, but it didn’t worked out because of the clip path.

Feel free to close this if you like to leave the triangle at its current dimensions.

### CODE REVIEW

**Comment by Haroenv** [comment]
What's the advantage of making this 10% less high and less wide, why don't you edit the overall size?

**Comment by mischah** [comment]
The triangle gets the same size in both variants,
The advantage is that you have less whitespace between the logo and the side of the triangle.

**Comment by Haroenv** [comment]
ah, that's an option, or putting the size of the logo > 50%50% would work too, right? IMO, that's better because the triangle is the `200px`or whatever size you ask it to be then.

**Comment by mischah** [comment]
yeah. you’re totally right. would love to see the image more centered.

I would go for the following dimensions of the anchor element:

``` css
height: 180px;
width: 180px;
```

and you could apply something like the following to the image:

``` css
width: 50%;
height: 60%;
position: absolute;
bottom: 0px;
left: 10px;
```

**Comment by Haroenv** [comment]
Yep, and ideally the size of the anchor would be accessible somewhere, like those variables I used. I'll try to see what your idea says.

**Comment by Haroenv** [comment]
I've done it, and it looks better indeed. Didn't use this branch though, you could delete this one

**Comment by mischah** [comment]
:ok_hand:

**Pull request closed without merging**
